import { ChatGPTAPI, ChatGPTUnofficialProxyAPI } from 'chatgpt'

  const api = new ChatGPTAPI({ apiKey: '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' })

  const api2 = new ChatGPTUnofficialProxyAPI({ accessToken: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJlbW9uMzMxQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJnZW9pcF9jb3VudHJ5IjoiQkQifSwiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS9hdXRoIjp7InVzZXJfaWQiOiJ1c2VyLW5sQWpSUUh4VGdsaXlSNkEyZGV3QVlRWiJ9LCJpc3MiOiJodHRwczovL2F1dGgwLm9wZW5haS5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMTY2Njk0MTYyNDU3OTExMDAzMjQiLCJhdWQiOlsiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS92MSIsImh0dHBzOi8vb3BlbmFpLm9wZW5haS5hdXRoMGFwcC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjc2NTIyOTk4LCJleHAiOjE2Nzc3MzI1OTgsImF6cCI6IlRkSkljYmUxNldvVEh0Tjk1bnl5d2g1RTR5T282SXRHIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCBtb2RlbC5yZWFkIG1vZGVsLnJlcXVlc3Qgb3JnYW5pemF0aW9uLnJlYWQgb2ZmbGluZV9hY2Nlc3MifQ.ZXu7U9PAthvYeOltrLEjoDfdsnzWb2I-_vuu-NOKFffCn0iUGcpsXNFSvzFpDSB55iZmsJRpd69Cow_JS6cDfa1XB-lYA1TwisYak9yy2g8Sf-jlFxGAIbfpEcEZ4RWSooec86scsGS2Kzc4uvcEOL4G102qgtvGQI-JWy-4L5dke76Xf3T9ArxUO2c_dwZeqY3xcR8YSNuym9bdCuOYUReQnEZKfcY3gErvlWQHjPMIGoDOubSHVXDQaokc5V5SSvLCC9j9W8Egp2MZrZF1HRBy23-TZtUP_LV-i8jOvc-ewd2BQnewRcp3OF1CwTOXJDYcWYGlm63IrqDmk6pmNA' })

// send a message and wait for the response
let res = await api2.sendMessage("Have we just witnessed ChatGPT completely transform the working world? I've been using it for a while and I feel like I really don't need to hire that many people for my small business now.")
console.log(res.text)

